CREATE TABLE customer (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_name VARCHAR(255)                            NOT NULL,
    customer_cash NUMERIC(19, 2)                            NOT NULL, -- Или DECIMAL(19,2)
    is_deleted  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE pizza (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_pizza       VARCHAR(255)                            NOT NULL,
    price_pizza      NUMERIC(19, 2)                           NOT NULL, -- Или DECIMAL(19,2)
    is_deleted BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_pizza PRIMARY KEY (id)
);

CREATE TABLE order_entity ( -- Имя изменено, чтобы соответствовать соглашениям
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT, -- Make it nullable to allow orders without customer
    quantity INTEGER NOT NULL,
    total_price NUMERIC(19, 2) NOT NULL,
    CONSTRAINT pk_order_entity PRIMARY KEY (id)
);

CREATE TABLE order_pizza ( -- Промежуточная таблица для ManyToMany связи
    order_id BIGINT NOT NULL,
    pizza_id BIGINT NOT NULL,
    CONSTRAINT pk_order_pizza PRIMARY KEY (order_id, pizza_id)
);


ALTER TABLE order_entity ADD CONSTRAINT FK_ORDER_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);
ALTER TABLE order_pizza ADD CONSTRAINT FK_ORDER_PIZZA_ON_ORDER FOREIGN KEY (order_id) REFERENCES order_entity (id);
ALTER TABLE order_pizza ADD CONSTRAINT FK_ORDER_PIZZA_ON_PIZZA FOREIGN KEY (pizza_id) REFERENCES pizza (id);